openapi: 3.1.0
info:
  version: 1.0.0
  title: <Контакти>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Книга контактів>
tags:

servers:
  - url: http://localhost:3000
  - url:

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    patch:
      $ref: ../swagger/paths/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
